<?php

namespace AppBundle\Repository;

/**
 * Profil_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Profil_userRepository extends \Doctrine\ORM\EntityRepository
{
}
